<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Backend.Application.csproj" />
    <ProjectReference Include="..\Backend.Contracts\Backend.Contracts.csproj" />
    <ProjectReference Include="..\Domain\Backend.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistence\Mock\Users\" />
  </ItemGroup>

</Project>
