<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Orders\**" />
    <EmbeddedResource Remove="Orders\**" />
    <None Remove="Orders\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Backend.Contracts\Backend.Contracts.csproj" />
    <ProjectReference Include="..\Domain\Backend.Domain.csproj" />
  </ItemGroup>

</Project>
